-- Privilege Imoveis - Supabase complete setup
-- Execute este arquivo no Supabase SQL Editor.
-- Ele cria a base para: imoveis, admin/corretores, leads, analytics,
-- favoritos, comparacao, storage de imagens e permissoes RLS.

create extension if not exists pgcrypto;

create table if not exists public.user_roles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'corretor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- 1. Helpers de permissoes
-- =========================

create or replace function public.current_user_role()
returns text
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (
      select role
      from public.user_roles
      where id = auth.uid()
      limit 1
    ),
    'anon'
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.current_user_role() = 'admin';
$$;

create or replace function public.is_staff()
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.current_user_role() in ('admin', 'corretor');
$$;

-- =========================
-- 2. Usuarios, roles e equipe
-- =========================

create table if not exists public.user_roles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'corretor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brokers (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  phone text,
  whatsapp text,
  avatar_url text,
  bio text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  role_to_apply text;
begin
  -- O primeiro usuario criado vira admin automaticamente.
  if not exists (select 1 from public.user_roles where role = 'admin') then
    role_to_apply := 'admin';
  else
    role_to_apply := 'corretor';
  end if;

  insert into public.user_roles (id, role)
  values (new.id, role_to_apply)
  on conflict (id) do nothing;

  insert into public.brokers (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', new.email)
  )
  on conflict (id) do update set
    email = excluded.email,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_privilege on auth.users;
create trigger on_auth_user_created_privilege
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.set_user_role(target_email text, new_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid;
begin
  if new_role not in ('admin', 'corretor') then
    raise exception 'Role invalida: %', new_role;
  end if;

  -- Permite configurar o primeiro admin mesmo se ainda nao existir admin.
  if exists (select 1 from public.user_roles where role = 'admin')
     and not public.is_admin() then
    raise exception 'Apenas administradores podem alterar permissoes.';
  end if;

  select id into target_id
  from auth.users
  where email = target_email
  limit 1;

  if target_id is null then
    raise exception 'Usuario nao encontrado: %', target_email;
  end if;

  insert into public.user_roles (id, role, updated_at)
  values (target_id, new_role, now())
  on conflict (id) do update set
    role = excluded.role,
    updated_at = now();
end;
$$;

-- =========================
-- 3. Imoveis
-- =========================

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  owner_id uuid references auth.users(id) on delete set null default auth.uid(),
  broker_id uuid references auth.users(id) on delete set null,
  title text not null default '',
  slug text not null unique,
  description text not null default '',
  location text not null default '',
  latitude double precision,
  longitude double precision,
  category text not null default 'Casas',
  type text,
  status text not null default 'ativo'
    check (status in ('ativo', 'reservado', 'vendido', 'rascunho', 'inativo')),
  price text not null default '',
  condominium text,
  iptu text,
  bedrooms integer not null default 0 check (bedrooms >= 0),
  bathrooms integer not null default 0 check (bathrooms >= 0),
  garage integer not null default 0 check (garage >= 0),
  area text,
  featured boolean not null default false,
  images text[] not null default '{}',
  videos text[] not null default '{}',
  virtual_tour_url text,
  meta_title text,
  meta_description text,
  keywords text[] not null default '{}',
  og_image text,
  whatsapp text,
  external_url text
);

alter table public.properties add column if not exists updated_at timestamptz not null default now();
alter table public.properties add column if not exists owner_id uuid references auth.users(id) on delete set null default auth.uid();
alter table public.properties add column if not exists broker_id uuid references auth.users(id) on delete set null;
alter table public.properties add column if not exists latitude double precision;
alter table public.properties add column if not exists longitude double precision;
alter table public.properties add column if not exists type text;
alter table public.properties add column if not exists status text not null default 'ativo';
alter table public.properties add column if not exists condominium text;
alter table public.properties add column if not exists iptu text;
alter table public.properties add column if not exists videos text[] not null default '{}';
alter table public.properties add column if not exists virtual_tour_url text;
alter table public.properties add column if not exists meta_title text;
alter table public.properties add column if not exists meta_description text;
alter table public.properties add column if not exists keywords text[] not null default '{}';
alter table public.properties add column if not exists og_image text;
alter table public.properties add column if not exists whatsapp text;
alter table public.properties add column if not exists external_url text;

create index if not exists properties_slug_idx on public.properties (slug);
create index if not exists properties_category_idx on public.properties (category);
create index if not exists properties_status_idx on public.properties (status);
create index if not exists properties_owner_idx on public.properties (owner_id);
create index if not exists properties_created_at_idx on public.properties (created_at desc);

-- =========================
-- 4. Leads e CRM basico
-- =========================

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  email text,
  source text not null default 'site',
  status text not null default 'novo'
    check (status in ('novo', 'em_atendimento', 'visita_agendada', 'convertido', 'perdido')),
  property_id bigint references public.properties(id) on delete set null,
  property_title text,
  broker_id uuid references auth.users(id) on delete set null,
  page_path text,
  notes text
);

alter table public.leads add column if not exists updated_at timestamptz not null default now();
alter table public.leads add column if not exists broker_id uuid references auth.users(id) on delete set null;
alter table public.leads add column if not exists notes text;

create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_property_idx on public.leads (property_id);
create index if not exists leads_created_at_idx on public.leads (created_at desc);

-- =========================
-- 5. Analytics, favoritos e comparacao
-- =========================

create table if not exists public.property_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  property_id bigint references public.properties(id) on delete cascade,
  path text,
  referrer text,
  user_agent text,
  session_id text,
  ip_hash text
);

create table if not exists public.property_favorites (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  property_id bigint not null references public.properties(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  session_id text,
  unique (property_id, user_id),
  unique (property_id, session_id)
);

create table if not exists public.property_comparisons (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  property_id bigint not null references public.properties(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  session_id text,
  unique (property_id, user_id),
  unique (property_id, session_id)
);

create index if not exists property_views_property_idx on public.property_views (property_id);
create index if not exists property_favorites_property_idx on public.property_favorites (property_id);
create index if not exists property_comparisons_property_idx on public.property_comparisons (property_id);

-- =========================
-- 6. Configuracoes do sistema
-- =========================

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.site_settings (key, value)
values
  ('brand', '{"name":"Privilege Imoveis","phone":"(83) 99999-9999","email":"contato@privilegeimoveis.com.br"}'),
  ('integrations', '{"googleAnalytics":"","metaPixel":"","microsoftClarity":"","whatsapp":"5583999999999"}')
on conflict (key) do nothing;

-- =========================
-- 7. Storage para imagens
-- =========================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'property-images',
  'property-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = true,
  file_size_limit = 10485760,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/avif'];

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'property-videos',
  'property-videos',
  true,
  104857600,
  array['video/mp4', 'video/webm', 'video/quicktime']
)
on conflict (id) do update set
  public = true,
  file_size_limit = 104857600,
  allowed_mime_types = array['video/mp4', 'video/webm', 'video/quicktime'];

-- =========================
-- 8. Updated_at automatico
-- =========================

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_properties_updated_at on public.properties;
create trigger touch_properties_updated_at
before update on public.properties
for each row execute function public.touch_updated_at();

drop trigger if exists touch_leads_updated_at on public.leads;
create trigger touch_leads_updated_at
before update on public.leads
for each row execute function public.touch_updated_at();

drop trigger if exists touch_brokers_updated_at on public.brokers;
create trigger touch_brokers_updated_at
before update on public.brokers
for each row execute function public.touch_updated_at();

-- =========================
-- 9. RLS
-- =========================

alter table public.user_roles enable row level security;
alter table public.brokers enable row level security;
alter table public.properties enable row level security;
alter table public.leads enable row level security;
alter table public.property_views enable row level security;
alter table public.property_favorites enable row level security;
alter table public.property_comparisons enable row level security;
alter table public.site_settings enable row level security;

-- user_roles
drop policy if exists "Admins manage roles" on public.user_roles;
drop policy if exists "Users can read own role" on public.user_roles;
create policy "Users can read own role"
on public.user_roles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "Admins read roles" on public.user_roles;
create policy "Admins read roles"
on public.user_roles for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins insert roles" on public.user_roles;
create policy "Admins insert roles"
on public.user_roles for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins update roles" on public.user_roles;
create policy "Admins update roles"
on public.user_roles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins delete roles" on public.user_roles;
create policy "Admins delete roles"
on public.user_roles for delete
to authenticated
using (public.is_admin());

-- brokers
drop policy if exists "Admins manage brokers" on public.brokers;
drop policy if exists "Public can read active brokers" on public.brokers;
create policy "Public can read active brokers"
on public.brokers for select
to anon, authenticated
using (active = true or public.is_staff());

drop policy if exists "Admins and owners insert brokers" on public.brokers;
create policy "Admins and owners insert brokers"
on public.brokers for insert
to authenticated
with check (public.is_admin() or id = auth.uid());

drop policy if exists "Admins and owners update brokers" on public.brokers;
create policy "Admins and owners update brokers"
on public.brokers for update
to authenticated
using (public.is_admin() or id = auth.uid())
with check (public.is_admin() or id = auth.uid());

drop policy if exists "Admins delete brokers" on public.brokers;
create policy "Admins delete brokers"
on public.brokers for delete
to authenticated
using (public.is_admin());

-- properties
drop policy if exists "Public can read published properties" on public.properties;
create policy "Public can read published properties"
on public.properties for select
to anon, authenticated
using (status = 'ativo' or public.is_staff());

drop policy if exists "Staff can create properties" on public.properties;
create policy "Staff can create properties"
on public.properties for insert
to authenticated
with check (public.is_staff());

drop policy if exists "Staff can update allowed properties" on public.properties;
create policy "Staff can update allowed properties"
on public.properties for update
to authenticated
using (public.is_admin() or owner_id = auth.uid() or broker_id = auth.uid())
with check (public.is_admin() or owner_id = auth.uid() or broker_id = auth.uid());

drop policy if exists "Admins can delete properties" on public.properties;
create policy "Admins can delete properties"
on public.properties for delete
to authenticated
using (public.is_admin());

-- leads
drop policy if exists "Public can create leads" on public.leads;
create policy "Public can create leads"
on public.leads for insert
to anon, authenticated
with check (true);

drop policy if exists "Staff can read leads" on public.leads;
create policy "Staff can read leads"
on public.leads for select
to authenticated
using (public.is_staff());

drop policy if exists "Staff can update leads" on public.leads;
create policy "Staff can update leads"
on public.leads for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

-- property_views
drop policy if exists "Public can create property views" on public.property_views;
create policy "Public can create property views"
on public.property_views for insert
to anon, authenticated
with check (true);

drop policy if exists "Staff can read property views" on public.property_views;
create policy "Staff can read property views"
on public.property_views for select
to authenticated
using (public.is_staff());

-- favorites
drop policy if exists "Public can create favorites" on public.property_favorites;
create policy "Public can create favorites"
on public.property_favorites for insert
to anon, authenticated
with check (true);

drop policy if exists "Users can read own favorites and staff can read all" on public.property_favorites;
create policy "Users can read own favorites and staff can read all"
on public.property_favorites for select
to anon, authenticated
using (public.is_staff() or user_id = auth.uid() or session_id is not null);

drop policy if exists "Users can delete own favorites" on public.property_favorites;
create policy "Users can delete own favorites"
on public.property_favorites for delete
to anon, authenticated
using (public.is_staff() or user_id = auth.uid() or session_id is not null);

-- comparisons
drop policy if exists "Public can create comparisons" on public.property_comparisons;
create policy "Public can create comparisons"
on public.property_comparisons for insert
to anon, authenticated
with check (true);

drop policy if exists "Users can read own comparisons and staff can read all" on public.property_comparisons;
create policy "Users can read own comparisons and staff can read all"
on public.property_comparisons for select
to anon, authenticated
using (public.is_staff() or user_id = auth.uid() or session_id is not null);

drop policy if exists "Users can delete own comparisons" on public.property_comparisons;
create policy "Users can delete own comparisons"
on public.property_comparisons for delete
to anon, authenticated
using (public.is_staff() or user_id = auth.uid() or session_id is not null);

-- settings
drop policy if exists "Admins manage site settings" on public.site_settings;
drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "Admins insert site settings" on public.site_settings;
create policy "Admins insert site settings"
on public.site_settings for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins update site settings" on public.site_settings;
create policy "Admins update site settings"
on public.site_settings for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins delete site settings" on public.site_settings;
create policy "Admins delete site settings"
on public.site_settings for delete
to authenticated
using (public.is_admin());

-- storage policies
drop policy if exists "Public can read property images" on storage.objects;
create policy "Public can read property images"
on storage.objects for select
to anon, authenticated
using (bucket_id in ('property-images', 'property-videos'));

drop policy if exists "Staff can upload property images" on storage.objects;
create policy "Staff can upload property images"
on storage.objects for insert
to authenticated
with check (
  bucket_id in ('property-images', 'property-videos')
  and public.is_staff()
);

drop policy if exists "Staff can update property images" on storage.objects;
create policy "Staff can update property images"
on storage.objects for update
to authenticated
using (
  bucket_id in ('property-images', 'property-videos')
  and public.is_staff()
)
with check (
  bucket_id in ('property-images', 'property-videos')
  and public.is_staff()
);

drop policy if exists "Staff can delete property images" on storage.objects;
create policy "Staff can delete property images"
on storage.objects for delete
to authenticated
using (
  bucket_id in ('property-images', 'property-videos')
  and public.is_staff()
);

-- =========================
-- 10. Views uteis para admin
-- =========================

create or replace view public.property_admin_metrics as
select
  p.id,
  p.title,
  p.slug,
  p.category,
  p.status,
  p.featured,
  p.created_at,
  count(distinct v.id) as views_count,
  count(distinct f.id) as favorites_count,
  count(distinct l.id) as leads_count
from public.properties p
left join public.property_views v on v.property_id = p.id
left join public.property_favorites f on f.property_id = p.id
left join public.leads l on l.property_id = p.id
group by p.id;

-- =========================
-- 11. Como criar o admin master
-- =========================

-- 1) Crie o usuario em Authentication > Users no Supabase.
-- 2) Depois rode este comando trocando o email:
--
-- select public.set_user_role('seu-email@dominio.com', 'admin');
--
-- Observacao: se ainda nao existir nenhum admin, a funcao permite promover
-- o primeiro usuario. Novos usuarios criados depois do primeiro entram como corretor.
